/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.0.20
 * Generated at: 2015-07-24 06:14:52 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.JSP;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import java.util.*;
import com.qst.francis.pojo.User;

public final class admin_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(2);
    _jspx_dependants.put("/WEB-INF/lib/standard-1.1.2.jar", Long.valueOf(1437466512864L));
    _jspx_dependants.put("jar:file:/F:/青软实训/FinalWork/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/dsgqxxw/WEB-INF/lib/standard-1.1.2.jar!/META-INF/c.tld", Long.valueOf(1098682290000L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("java.util");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_classes = new java.util.HashSet<>();
    _jspx_imports_classes.add("com.qst.francis.pojo.User");
  }

  private javax.el.ExpressionFactory _el_expressionfactory;
  private org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public void _jspInit() {
    _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
    _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

final java.lang.String _jspx_method = request.getMethod();
if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
return;
}

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html PUBLIC \"-//W3C//DTD HTML 4.01 Transitional//EN\" \"http://www.w3.org/TR/html4/loose.dtd\">\r\n");
      out.write("<html>\r\n");
      out.write("\r\n");
      out.write("   \t");

   		User user = (User)session.getAttribute("nowuser");
   		if(user == null){
   			response.sendRedirect("/dsgqxxw/JSP/login.jsp");
   		}
   	
      out.write("\r\n");
      out.write("    <head>\r\n");
      out.write("        <meta charset=\"utf-8\">\r\n");
      out.write("        <title>后台付费状态检索</title>\r\n");
      out.write("        <link rel=\"shortcut icon\" type=\"image/x-icon\" href=\"../images/my_logo.gif\" />\r\n");
      out.write("        <link rel=\"stylesheet\" type=\"text/css\" href=\"../css/admin.css\">\r\n");
      out.write("        <script>\r\n");
      out.write("            function showdetailinfo(){\r\n");
      out.write("                document.getElementById(\"content-body\").src=\"admin_check_info.html\";\r\n");
      out.write("            }\r\n");
      out.write("            function judgeDigit(){\r\n");
      out.write("            \tvar reg = /^[0-9]+$/;\r\n");
      out.write("            \tvar queryid = document.getElementById(\"enterhadcost\").value;\r\n");
      out.write("            \tif(!reg.test(queryid)){\r\n");
      out.write("            \t\talert(\"请输入数字\");\r\n");
      out.write("            \t\treturn false;\r\n");
      out.write("            \t}\r\n");
      out.write("            \treturn true;\r\n");
      out.write("            }\r\n");
      out.write("            function judgeDigitOrNull(){\r\n");
      out.write("            \tvar reg = /^[0-9]*$/;\r\n");
      out.write("            \tvar queryid = document.getElementById(\"enteruserid\").value;\r\n");
      out.write("            \tif(!reg.test(queryid)){\r\n");
      out.write("            \t\talert(\"请输入数字\");\r\n");
      out.write("            \t\treturn false;\r\n");
      out.write("            \t}\r\n");
      out.write("            \treturn true;\r\n");
      out.write("            }\r\n");
      out.write("        </script>\r\n");
      out.write("    </head>\r\n");
      out.write("    <body>\r\n");
      out.write("        <div class=\"container\">\r\n");
      out.write("            <!--top-->\r\n");
      out.write("            <div class=\"top\">\r\n");
      out.write("                <div class=\"admin-index\">\r\n");
      out.write("                    <a href=\"index.jsp\"><img src=\"../images/admin_index.gif\"></a>\r\n");
      out.write("                </div>\r\n");
      out.write("                <div class=\"admin-exit\">\r\n");
      out.write("                    <a href=\"/dsgqxxw/logoffAction\"><img src=\"../images/admin_exit.gif\"></a>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("            \r\n");
      out.write("            <!--    body        -->\r\n");
      out.write("            <div class=\"div-body\">\r\n");
      out.write("                <div class=\"div-body-left\">\r\n");
      out.write("                    <!--        iframe            -->\r\n");
      out.write("                    <iframe id=\"content-body\" name=\"content_body\" src=\"../html/admin_welcome.html\"></iframe>\r\n");
      out.write("                </div>\r\n");
      out.write("                \r\n");
      out.write("                <div class=\"div-body-right\">\r\n");
      out.write("                    <ul>\r\n");
      out.write("                    \t<li>\r\n");
      out.write("                    \t\t<p class=\"li-top-right\">用户设置(请输入用户ID)</p>\r\n");
      out.write("                            <div class=\"div-right-top\">\r\n");
      out.write("                            \t<form action=\"../queryIdUserAction\" method=\"GET\" target=\"content_body\" onsubmit=\"return judgeDigitOrNull()\">\r\n");
      out.write("\t                                <input type=\"text\" name=\"enteruserid\" id=\"enteruserid\" size=\"16px\">\r\n");
      out.write("\t                                <input type=\"submit\" name=\"searchuser\" id=\"searchuser\" value=\"查询\">\r\n");
      out.write("                            \t</form>\r\n");
      out.write("                            </div>\r\n");
      out.write("                    \t</li>\r\n");
      out.write("                        <li>\r\n");
      out.write("                            <p class=\"li-top-right\">显示方式</p>\r\n");
      out.write("                            <div class=\"div-right-top\">\r\n");
      out.write("\t                            <form action=\"../queryStateInfoAction\" method=\"post\" target=\"content_body\">\r\n");
      out.write("\t                                <fieldset>\r\n");
      out.write("\t                                    <legend align=\"left\">★付费状态</legend>\r\n");
      out.write("\t                                    <input type=\"radio\" name=\"cost\" value=\"0\">未付费\r\n");
      out.write("\t                                    <input type=\"radio\" name=\"cost\" value=\"1\">已付费\r\n");
      out.write("\t                                    <input type=\"radio\" name=\"cost\" value=\"-1\" checked=\"checked\">全部\r\n");
      out.write("\t                                </fieldset>\r\n");
      out.write("\t                                <fieldset>\r\n");
      out.write("\t                                    <legend align=\"left\">★审核状态</legend>\r\n");
      out.write("\t                                    <input type=\"radio\" name=\"check\" value=\"0\">未审核\r\n");
      out.write("\t                                    <input type=\"radio\" name=\"check\" value=\"1\">已审核\r\n");
      out.write("\t                                    <input type=\"radio\" name=\"check\" value=\"-1\" checked=\"checked\">全部\r\n");
      out.write("\t                                </fieldset>\r\n");
      out.write("\t                                <div class=\"select-jobinfo\">\r\n");
      out.write("\t                                    信息类别：\r\n");
      out.write("\t                                    <select style=\"border:1px solid #999\" name=\"selectinfooption\">\r\n");
      out.write("\t                                        <option value=\"0\" selected=\"selected\">&nbsp;</option>\r\n");
      out.write("\t                                        <option value=\"1\">招聘信息</option>\r\n");
      out.write("\t                                        <option value=\"2\">培训信息</option>\r\n");
      out.write("\t                                        <option value=\"3\">求职信息</option>\r\n");
      out.write("\t                                        <option value=\"4\">家教信息</option>\r\n");
      out.write("\t\t\t\t\t                        <option value=\"5\">房屋信息</option>\r\n");
      out.write("\t\t\t\t\t                        <option value=\"6\">求购信息</option>\r\n");
      out.write("\t\t\t\t\t                        <option value=\"7\">招商引资</option>\r\n");
      out.write("\t\t\t\t\t                        <option value=\"8\">公寓信息</option>\r\n");
      out.write("\t\t\t\t\t                        <option value=\"9\">车辆信息</option>\r\n");
      out.write("\t\t\t\t\t                        <option value=\"10\">出售信息</option>\r\n");
      out.write("\t\t\t\t\t                        <option value=\"11\">寻找启示</option>\r\n");
      out.write("\t                                    </select>\r\n");
      out.write("\t                                    <input type=\"submit\" value=\"显示\" name=\"show\">\r\n");
      out.write("\t                                </form>\r\n");
      out.write("                                </div>\r\n");
      out.write("                            </div>\r\n");
      out.write("                        </li>\r\n");
      out.write("                        <li>\r\n");
      out.write("                            <p class=\"li-top-right\">付费设置</p>\r\n");
      out.write("                            <div class=\"div-right-top\">\r\n");
      out.write("                            \t<form action=\"../queryIdInfoAction\" method=\"GET\" target=\"content_body\" onsubmit=\"return judgeDigit()\">\r\n");
      out.write("\t                                <p>请输入要设为已付费状态的信息ID：<br></p>\r\n");
      out.write("\t                                <input type=\"text\" name=\"enterhadcost\" id=\"enterhadcost\" size=\"16px\">\r\n");
      out.write("\t                                <input type=\"submit\" name=\"searchcost\" id=\"searchcost\" value=\"查询\">\r\n");
      out.write("                            \t</form>\r\n");
      out.write("                            </div>\r\n");
      out.write("                        </li>\r\n");
      out.write("                        <li>\r\n");
      out.write("                            <p class=\"li-top-right\">日历</p>\r\n");
      out.write("                            <!--    获取正确时间并显示     -->\r\n");
      out.write("                            <iframe id=\"content-time\" name=\"content-time\" src=\"../html/calender.html\"></iframe>\r\n");
      out.write("                        </li>\r\n");
      out.write("                    </ul>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("        \r\n");
      out.write("    </body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
