/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.0.20
 * Generated at: 2015-07-24 06:50:42 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.JSP;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import java.util.*;
import com.qst.francis.pojo.User;

public final class index_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(2);
    _jspx_dependants.put("/WEB-INF/lib/standard-1.1.2.jar", Long.valueOf(1437466512864L));
    _jspx_dependants.put("jar:file:/F:/青软实训/FinalWork/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/dsgqxxw/WEB-INF/lib/standard-1.1.2.jar!/META-INF/c.tld", Long.valueOf(1098682290000L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("java.util");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_classes = new java.util.HashSet<>();
    _jspx_imports_classes.add("com.qst.francis.pojo.User");
  }

  private javax.el.ExpressionFactory _el_expressionfactory;
  private org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public void _jspInit() {
    _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
    _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

final java.lang.String _jspx_method = request.getMethod();
if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
return;
}

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=utf-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html PUBLIC \"-//W3C//DTD HTML 4.01 Transitional//EN\" \"http://www.w3.org/TR/html4/loose.dtd\">\r\n");
      out.write("<html>\r\n");
      out.write("    <head>\r\n");
      out.write("        <meta charset=\"utf-8\">\r\n");
      out.write("        <title>Index</title>\r\n");
      out.write("        <link rel=\"shortcut icon\" type=\"image/x-icon\" href=\"../images/my_logo.gif\" />\r\n");
      out.write("        <link rel=\"stylesheet\" type=\"text/css\" href=\"../css/index.css\">\r\n");
      out.write("        <script>\r\n");
      out.write("            function change_jobinfo(){\r\n");
      out.write("                document.getElementById(\"content-indexbody-right\").src=\"jobinfo.html\";\r\n");
      out.write("            }\r\n");
      out.write("            function change_index(){\r\n");
      out.write("                document.getElementById(\"content-indexbody-right\").src=\"recommendInfo.jsp\";\r\n");
      out.write("            }\r\n");
      out.write("            function change_searchAnswer(){\r\n");
      out.write("                document.getElementById(\"content-indexbody-right\").src=\"searchAnswer.html\";\r\n");
      out.write("            }\r\n");
      out.write("        </script>\r\n");
      out.write("    </head>\r\n");
      out.write("    <body class=\"index-body\">\r\n");
      out.write("        <div class=\"container\">\r\n");
      out.write("            <div class=\"top-message\">\r\n");
      out.write("                <div class=\"top-message-left\">\r\n");
      out.write("                    <a href=\"releaseInfo.jsp\" target=\"content-indexbody-right\">[发布信息]</a>\r\n");
      out.write("                    <a href=\"admin.jsp\">[进入后台]</a>\r\n");
      out.write("                </div>\r\n");
      out.write("                <div class=\"top-message-right\">\r\n");
      out.write("                    <a href=\"#\">设为主页</a>-\r\n");
      out.write("                    <a href=\"#\">收藏本页</a>-\r\n");
      out.write("                    <a href=\"#\">联系我们</a>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("            \r\n");
      out.write("            <div class=\"top-pic\">\r\n");
      out.write("            </div>\r\n");
      out.write("            <div class=\"top-menu\">\r\n");
      out.write("                <table class=\"table-top-menu\" id=\"tableTopMenu\">\r\n");
      out.write("                    <tr>\r\n");
      out.write("                        <td><span class=\"likea\" onclick=\"change_index()\">首&nbsp;&nbsp;页</span></td>\r\n");
      out.write("<!--                        <td><span class=\"likea\" onclick=\"change_jobinfo()\">招聘信息</span></td>-->\r\n");
      out.write("                        <td><a href=\"/dsgqxxw/queryByTypeId?infoTypeId=1\" target=\"content-indexbody-right\" class=\"likea\">招聘信息</a></td>\r\n");
      out.write("                        <td><a href=\"/dsgqxxw/queryByTypeId?infoTypeId=2\" target=\"content-indexbody-right\" class=\"likea\">培训信息</a></td>\r\n");
      out.write("                        <td><a href=\"/dsgqxxw/queryByTypeId?infoTypeId=5\" target=\"content-indexbody-right\" class=\"likea\">房屋信息</a></td>\r\n");
      out.write("                        <td><a href=\"/dsgqxxw/queryByTypeId?infoTypeId=6\" target=\"content-indexbody-right\" class=\"likea\">求购信息</a></td>\r\n");
      out.write("                        <td><a href=\"/dsgqxxw/queryByTypeId?infoTypeId=7\" target=\"content-indexbody-right\" class=\"likea\">招商引资</a></td>\r\n");
      out.write("                    </tr>\r\n");
      out.write("                    <tr>\r\n");
      out.write("                        <td><a href=\"/dsgqxxw/queryByTypeId?infoTypeId=8\" target=\"content-indexbody-right\" class=\"likea\">公寓信息</a></td>\r\n");
      out.write("                        <td><a href=\"/dsgqxxw/queryByTypeId?infoTypeId=3\" target=\"content-indexbody-right\" class=\"likea\">求职信息</a></td>\r\n");
      out.write("                        <td><a href=\"/dsgqxxw/queryByTypeId?infoTypeId=4\" target=\"content-indexbody-right\" class=\"likea\">家教信息</a></td>\r\n");
      out.write("                        <td><a href=\"/dsgqxxw/queryByTypeId?infoTypeId=9\" target=\"content-indexbody-right\" class=\"likea\">车辆信息</a></td>\r\n");
      out.write("                        <td><a href=\"/dsgqxxw/queryByTypeId?infoTypeId=10\" target=\"content-indexbody-right\" class=\"likea\">出售信息</a></td>\r\n");
      out.write("                        <td><a href=\"/dsgqxxw/queryByTypeId?infoTypeId=11\" target=\"content-indexbody-right\" class=\"likea\">寻找启示</a></td>\r\n");
      out.write("                    </tr>\r\n");
      out.write("                </table>\r\n");
      out.write("            </div>\r\n");
      out.write("            \r\n");
      out.write("            <div class=\"top-midpic\">\r\n");
      out.write("            </div>\r\n");
      out.write("            \r\n");
      out.write("            <div class=\"div-indexbody-left\">\r\n");
      out.write("                <ul>\r\n");
      out.write("                    <li>\r\n");
      out.write("                        <div class=\"li-indexbody-left\">日历</div>\r\n");
      out.write("                        <!--    获取正确时间并显示     -->\r\n");
      out.write("                        <iframe id=\"content-time\" name=\"content-time\" src=\"../html/calender.html\" class=\"iframe-cale\"></iframe>\r\n");
      out.write("                    </li>\r\n");
      out.write("                    <li>\r\n");
      out.write("                    \t<form action=\"/dsgqxxw/queryByCondtionAction\" method=\"post\" target=\"content-indexbody-right\">\r\n");
      out.write("\t                        <div class=\"li-indexbody-left\">信息快速检索</div>\r\n");
      out.write("\t                        <div class=\"info-search\">\r\n");
      out.write("\t                            关键字： <input type=\"text\" name=\"coninput\" size=\"17px\"><br>\r\n");
      out.write("\t                            条&nbsp;件：\r\n");
      out.write("\t                            <select class=\"select-cond\" name=\"condition\" >\r\n");
      out.write("\t                                <option value=\"INFO_TYPE_NAME\">信息类型</option>\r\n");
      out.write("\t                                <option value=\"INFO_TITLE\">信息标题</option>\r\n");
      out.write("\t                                <option value=\"INFO_LINKMAN\">信息联系人</option>\r\n");
      out.write("\t                                <option value=\"INFO_PHONE\">信息联系电话</option>\r\n");
      out.write("\t                                <option value=\"INFO_EMAIL\">信息联系邮箱</option>\r\n");
      out.write("\t                                <option value=\"INFO_CONTENT\">信息内容</option>\r\n");
      out.write("\t                            </select>\r\n");
      out.write("\t                            <input type=\"submit\" name=\"index-search\" id=\"index-search\" value=\"搜索\"><br>               \r\n");
      out.write("\t                            搜索类型：\r\n");
      out.write("\t                            <input type=\"radio\" name=\"matchType\" id=\"matchall\" value=\"matchAll\">全字匹配\r\n");
      out.write("\t                            <input type=\"radio\" name=\"matchType\" id=\"matchsome\" value=\"matchSome\" checked=\"checked\">模糊匹配\r\n");
      out.write("\t                        </div>\r\n");
      out.write("                        </form>\r\n");
      out.write("                    </li>\r\n");
      out.write("                </ul>\r\n");
      out.write("            </div>\r\n");
      out.write("            <div class=\"div-indexbody-right\" id=\"div-indexbody-right-id\">\r\n");
      out.write("                <iframe id=\"content-indexbody-right\" name=\"content-indexbody-right\" src=\"recommendInfo.jsp\"></iframe>\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("    </body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
