/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.0.20
 * Generated at: 2015-07-23 01:41:52 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.JSP;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class recommendInfo_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_classes = null;
  }

  private javax.el.ExpressionFactory _el_expressionfactory;
  private org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public void _jspInit() {
    _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
    _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

final java.lang.String _jspx_method = request.getMethod();
if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
return;
}

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<!DOCTYPE html PUBLIC \"-//W3C//DTD HTML 4.01 Transitional//EN\" \"http://www.w3.org/TR/html4/loose.dtd\">\r\n");
      out.write("<html>\r\n");
      out.write("    <head>\r\n");
      out.write("        <meta charset=\"utf-8\">\r\n");
      out.write("        <title>Recommemd information</title>\r\n");
      out.write("        <style type=\"text/css\">\r\n");
      out.write("            #recommendinfo-container{\r\n");
      out.write("                clear: both;\r\n");
      out.write("                width: 100%;\r\n");
      out.write("                height: 850px;\r\n");
      out.write("            }\r\n");
      out.write("            #recommendinfo-div-left{\r\n");
      out.write("                width: 45%;\r\n");
      out.write("                height: 150px;\r\n");
      out.write("                float: left;\r\n");
      out.write("            }\r\n");
      out.write("            #recommendinfo-div-right{\r\n");
      out.write("                width: 45%;\r\n");
      out.write("                height: 150px;\r\n");
      out.write("                float: left;\r\n");
      out.write("            }\r\n");
      out.write("            ul{\r\n");
      out.write("                list-style: none;\r\n");
      out.write("            }\r\n");
      out.write("             #li-ad{\r\n");
      out.write("                clear: both;\r\n");
      out.write("                height: 85px;\r\n");
      out.write("                background-image: url(../images/pcard2.jpg);\r\n");
      out.write("                background-repeat: no-repeat;\r\n");
      out.write("                background-size: cover;\r\n");
      out.write("            }\r\n");
      out.write("            #list-ad{\r\n");
      out.write("                margin-left: -50px;\r\n");
      out.write("                list-style: none;\r\n");
      out.write("            }\r\n");
      out.write("            .infotable-info{\r\n");
      out.write("                width: 100%;\r\n");
      out.write("            }\r\n");
      out.write("            .infotable-info td{\r\n");
      out.write("                width: 45%;\r\n");
      out.write("                height: 110px;\r\n");
      out.write("                border: 1px solid #fff;\r\n");
      out.write("            }\r\n");
      out.write("            .infotable-title{\r\n");
      out.write("                background-color: #0a957a;\r\n");
      out.write("                color: #fff;\r\n");
      out.write("            }\r\n");
      out.write("            .float-bottom{\r\n");
      out.write("                float: right;\r\n");
      out.write("                bottom: 0px;\r\n");
      out.write("            }\r\n");
      out.write("            #recommendinfo-div{\r\n");
      out.write("                width: 100%;\r\n");
      out.write("                height: 150px;\r\n");
      out.write("                background-color: #ccc;\r\n");
      out.write("                padding-top: 20px;\r\n");
      out.write("            }\r\n");
      out.write("            #infoTable-div{\r\n");
      out.write("                width: 100%;\r\n");
      out.write("                height: 470px;\r\n");
      out.write("                background-color: #ccc;\r\n");
      out.write("            }\r\n");
      out.write("            #recommendinfo-container ul{\r\n");
      out.write("                list-style: none;\r\n");
      out.write("                margin-left: -30px;\r\n");
      out.write("            }\r\n");
      out.write("            #recommendinfo-container span{\r\n");
      out.write("                color: #0e3295;\r\n");
      out.write("            }\r\n");
      out.write("            .li-div{\r\n");
      out.write("                 padding-top: 20px\r\n");
      out.write("             }\r\n");
      out.write("        </style>\r\n");
      out.write("    </head>\r\n");
      out.write("    <body>\r\n");
      out.write("        <div id=\"recommendinfo-container\">\r\n");
      out.write("            <ul>\r\n");
      out.write("                <li class=\"li-div\"><span>■推荐信息『缴费专区』</span><br>\r\n");
      out.write("                    <div id=\"recommendinfo-div\">\r\n");
      out.write("                        <div id=\"recommendinfo-div-left\">\r\n");
      out.write("                            <ul>\r\n");
      out.write("                                <li>『寻找启示』寻找启示标题</li>\r\n");
      out.write("                                <li>『车辆信息』车辆信息标题</li>\r\n");
      out.write("                                <li>『求职信息』求职信息标题</li>\r\n");
      out.write("                                <li>『招商引资』招商引资标题</li>\r\n");
      out.write("                                <li>『房屋信息』房屋信息标题</li>\r\n");
      out.write("                                <li>『招聘信息』招聘信息标题</li>\r\n");
      out.write("                            </ul>\r\n");
      out.write("                        </div>\r\n");
      out.write("                        <div id=\"recommendinfo-div-right\">\r\n");
      out.write("                            <ul>\r\n");
      out.write("                                <li>『出售信息』出售信息标题</li>\r\n");
      out.write("                                <li>『家教信息』家教信息标题</li>\r\n");
      out.write("                                <li>『公寓信息』公寓信息标题</li>\r\n");
      out.write("                                <li>『求购信息』求购信息标题</li>\r\n");
      out.write("                                <li>『培训信息』培训信息标题</li>\r\n");
      out.write("                                <li>&nbsp;</li>\r\n");
      out.write("                            </ul>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </li>\r\n");
      out.write("                <li class=\"li-div\">\r\n");
      out.write("                    <ol id=\"list-ad\">\r\n");
      out.write("                        <li id=\"li-ad\"></li>\r\n");
      out.write("                    </ol>\r\n");
      out.write("                </li>\r\n");
      out.write("                <li class=\"li-div\"><span>■最新信息『免费专区』</span><br>\r\n");
      out.write("                    <div id=\"infoTable-div\">\r\n");
      out.write("                        <table class=\"infotable-info\">\r\n");
      out.write("                            <tr>\r\n");
      out.write("                                <td>\r\n");
      out.write("                                    <div class=\"infotable-title\">▲招聘信息</div>\r\n");
      out.write("                                    <p>发布信息标题</p>\r\n");
      out.write("                                    <div class=\"float-bottom\">更多...</div>\r\n");
      out.write("                                </td>\r\n");
      out.write("                                <td>\r\n");
      out.write("                                    <div class=\"infotable-title\">▲培训信息</div>\r\n");
      out.write("                                    <p>发布信息标题</p>\r\n");
      out.write("                                    <div class=\"float-bottom\">更多...</div>\r\n");
      out.write("                                </td>\r\n");
      out.write("                            </tr>\r\n");
      out.write("                            <tr>\r\n");
      out.write("                                <td>\r\n");
      out.write("                                    <div class=\"infotable-title\">▲公寓信息</div>\r\n");
      out.write("                                    <p>发布信息标题</p>\r\n");
      out.write("                                    <div class=\"float-bottom\">更多...</div>\r\n");
      out.write("                                </td>\r\n");
      out.write("                                <td>\r\n");
      out.write("                                    <div class=\"infotable-title\">▲求职信息</div>\r\n");
      out.write("                                    <p>发布信息标题</p>\r\n");
      out.write("                                    <div class=\"float-bottom\">更多...</div>\r\n");
      out.write("                                </td>\r\n");
      out.write("                            </tr>\r\n");
      out.write("                            <tr>\r\n");
      out.write("                                <td>\r\n");
      out.write("                                    <div class=\"infotable-title\">▲家教信息</div>\r\n");
      out.write("                                    <p>发布信息标题</p>\r\n");
      out.write("                                    <div class=\"float-bottom\">更多...</div>\r\n");
      out.write("                                </td>\r\n");
      out.write("                                <td>\r\n");
      out.write("                                    <div class=\"infotable-title\">▲车辆信息</div>\r\n");
      out.write("                                    <p>发布信息标题</p>\r\n");
      out.write("                                    <div class=\"float-bottom\">更多...</div>\r\n");
      out.write("                                </td>\r\n");
      out.write("                            </tr>\r\n");
      out.write("                            <tr>\r\n");
      out.write("                                <td>\r\n");
      out.write("                                    <div class=\"infotable-title\">▲出售信息</div>\r\n");
      out.write("                                    <p>发布信息标题</p>\r\n");
      out.write("                                    <div class=\"float-bottom\">更多...</div>\r\n");
      out.write("                                </td>\r\n");
      out.write("                                <td>\r\n");
      out.write("                                    <div class=\"infotable-title\">▲寻找信息</div>\r\n");
      out.write("                                    <p>发布信息标题</p>\r\n");
      out.write("                                    <div class=\"float-bottom\">更多...</div>\r\n");
      out.write("                                </td>\r\n");
      out.write("                            </tr>\r\n");
      out.write("                        </table>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </li>\r\n");
      out.write("            </ul>\r\n");
      out.write("        </div>\r\n");
      out.write("    </body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
