/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.0.20
 * Generated at: 2015-07-24 06:14:55 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.JSP;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class releaseInfo_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_classes = null;
  }

  private javax.el.ExpressionFactory _el_expressionfactory;
  private org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public void _jspInit() {
    _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
    _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

final java.lang.String _jspx_method = request.getMethod();
if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
return;
}

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<!DOCTYPE html PUBLIC \"-//W3C//DTD HTML 4.01 Transitional//EN\" \"http://www.w3.org/TR/html4/loose.dtd\">\r\n");
      out.write("<!-- 发布信息-->\r\n");
      out.write("<html>\r\n");
      out.write("    <head>\r\n");
      out.write("        <meta charset=\"utf-8\">\r\n");
      out.write("        <head>发布信息</head>\r\n");
      out.write("        <style type=\"text/css\">\r\n");
      out.write("            #container{\r\n");
      out.write("                width: 100%;\r\n");
      out.write("                height: auto;\r\n");
      out.write("                border: 1px solid #ccc;\r\n");
      out.write("                background-color: #eee;\r\n");
      out.write("            }\r\n");
      out.write("            .float-left{\r\n");
      out.write("                float: left;\r\n");
      out.write("            }\r\n");
      out.write("            .float-right{\r\n");
      out.write("                float: right;\r\n");
      out.write("            }\r\n");
      out.write("            .second-line{\r\n");
      out.write("                clear: both;\r\n");
      out.write("            }\r\n");
      out.write("            .second-line input{\r\n");
      out.write("                width: 70%;\r\n");
      out.write("            }\r\n");
      out.write("            span{\r\n");
      out.write("                background-color: #ddd;\r\n");
      out.write("            }\r\n");
      out.write("            textarea{\r\n");
      out.write("                width: 90%;\r\n");
      out.write("                height: 100px;\r\n");
      out.write("                \r\n");
      out.write("                resize: none;\r\n");
      out.write("                clear: both;\r\n");
      out.write("            }\r\n");
      out.write("            .div-foot{\r\n");
      out.write("                width: 90%;\r\n");
      out.write("                text-align: center;\r\n");
      out.write("            }\r\n");
      out.write("        </style>\r\n");
      out.write("        <script>\r\n");
      out.write("            function content_calc(){\r\n");
      out.write("                var total = document.getElementById(\"type_content\").value;\r\n");
      out.write("                document.getElementById(\"usedchar\").innerHTML = total.length;\r\n");
      out.write("                document.getElementById(\"remainderchar\").innerHTML = 500 - total.length;\r\n");
      out.write("            }\r\n");
      out.write("            function judgeSubmit(){\r\n");
      out.write("                var flag = true;\r\n");
      out.write("                if(document.getElementById(\"info_title\").value==\"\"){\r\n");
      out.write("                    alert(\"标题不可为空\");\r\n");
      out.write("                    flag = false;\r\n");
      out.write("                }\r\n");
      out.write("                if(document.getElementById(\"info_phone\").value==\"\"){\r\n");
      out.write("                    alert(\"联系电话不可为空\");\r\n");
      out.write("                    flag = false;\r\n");
      out.write("                }\r\n");
      out.write("                if(document.getElementById(\"info_user\").value==\"\"){\r\n");
      out.write("                    alert(\"联系人不可为空\");\r\n");
      out.write("                    flag = false;\r\n");
      out.write("                }\r\n");
      out.write("                if(document.getElementById(\"info_email\").value==\"\"){\r\n");
      out.write("                    alert(\"E-mail不可为空\");\r\n");
      out.write("                    flag = false;\r\n");
      out.write("                }\r\n");
      out.write("                return flag;\r\n");
      out.write("            }\r\n");
      out.write("        </script>\r\n");
      out.write("    </head>\r\n");
      out.write("    <body>\r\n");
      out.write("        <div id=\"container\">\r\n");
      out.write("            ■发布信息<br>\r\n");
      out.write("            <form action=\"../insertInfoAction\" method=\"post\" onSubmit=\"return judgeSubmit()\">\r\n");
      out.write("                <div class=\"float-left\">\r\n");
      out.write("                    信息类别:&nbsp;\r\n");
      out.write("                    <select name=\"info_type\" id=\"info-type\">\r\n");
      out.write("                        <option value=\"1\" selected=selected>招聘信息</option>\r\n");
      out.write("                        <option value=\"2\">培训信息</option>\r\n");
      out.write("                        <option value=\"3\">求职信息</option>\r\n");
      out.write("                        <option value=\"4\">家教信息</option>\r\n");
      out.write("                        <option value=\"5\">房屋信息</option>\r\n");
      out.write("                        <option value=\"6\">求购信息</option>\r\n");
      out.write("                        <option value=\"7\">招商引资</option>\r\n");
      out.write("                        <option value=\"8\">公寓信息</option>\r\n");
      out.write("                        <option value=\"9\">车辆信息</option>\r\n");
      out.write("                        <option value=\"10\">出售信息</option>\r\n");
      out.write("                        <option value=\"11\">寻找启示</option>\r\n");
      out.write("                    </select><br>\r\n");
      out.write("                </div>\r\n");
      out.write("                <div class=\"float-right\">\r\n");
      out.write("                    [信息标题最多不得超过40个字符]\r\n");
      out.write("                </div>\r\n");
      out.write("                <div class=\"second-line\">\r\n");
      out.write("                    信息标题:&nbsp;\r\n");
      out.write("                    <input type=\"text\" maxlength=\"40\" name=\"info_title\"  id=\"info_title\"><br>\r\n");
      out.write("                \r\n");
      out.write("                </div>\r\n");
      out.write("                信息内容:&nbsp;&nbsp;已用：<span id=\"usedchar\">0</span>个&nbsp;剩余：<span id=\"remainderchar\">500</span>个\r\n");
      out.write("                <div class=\"float-right\">[信息内容最多不得超过500个字符]</div>\r\n");
      out.write("                <br>\r\n");
      out.write("                <textarea class=\"content\" name=\"info_content\" maxlength=\"500\" oninput =\"content_calc()\" id=\"type_content\"></textarea><br>\r\n");
      out.write("                联系电话:&nbsp;<input type=\"text\" name=\"info_phone\"  id=\"info_phone\">[多个电话以逗号分隔！]<br>\r\n");
      out.write("                联 系 人:&nbsp;<input type=\"text\" name=\"info_user\" id=\"info_user\"><br>\r\n");
      out.write("                E - mail:&nbsp;<input type=\"text\" name=\"info_email\" id=\"info_email\"><br>\r\n");
      out.write("                <div class=\"div-foot\">\r\n");
      out.write("                    <input type=\"submit\" id=\"submitbtn\" value=\"发布\">\r\n");
      out.write("                    <input type=\"reset\" id=\"resetbtn\" value=\"重置\">\r\n");
      out.write("                </div>\r\n");
      out.write("            </form>\r\n");
      out.write("        </div>\r\n");
      out.write("    </body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
